# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4af95047fcc056a40ac060cefd3c8168dc510638f8f9f4aa1546a0cc15b7973eb4d4fb20a72094164d3f7dd974968b7706d94f62c0decd299f271daf4756131

test:
  secret_key_base: 236cddc946d8f50c53bc7f447467b915e1f1e0ccd374385ab341f84055246cb99c1570748894e86e73b4bd5895ec7bba5f7d5187fd4b514a92f381bc66efd8d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
